site_name: test

markdown_extensions:
  admonition: {}
  pymdownx.details: {}
  pymdownx.superfences: {}
  pymdownx.arithmatex: # required for equation display
    generic: true
  pymdownx.snippets: 
    url_download: true
  markdown_include.include:
    base_path: docs

nav:
- Pooler_1:
  - Home: 'docs/index_1.md'
- Pooler_2:
  - Home: 'docs/index_2.md'
